import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { TopMenuComponent } from "@/module/admin/component/TopMenuComponent"
import LeftNavBarComponent from "@/module/admin/component/LeftNavBarComponent"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="h-screen">
        <TopMenuComponent></TopMenuComponent>
        <div className="flex overflow-hidden bg-white pt-16 h-screen">
          <LeftNavBarComponent></LeftNavBarComponent>
          <div
            className="bg-gray-900 opacity-50 hidden fixed inset-0 z-10"
            id="sidebarBackdrop"
          ></div>
          <div
            id="main-content"
            className="h-full w-full bg-gray-50 relative overflow-y-auto"
          >
            <main>
              <div className="pt-6 px-4">{children}</div>
            </main>
          </div>
        </div>
      </body>
    </html>
  )
}
